name: Clean up the garbage

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      file_size_limit:
        description: '删除大于多少的文件 (例如: 10M, 50M)'
        required: true
        default: '10M'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v6
      with:
        repository: cluntop/tvbox
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0

    - name: Install git-filter-repo
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install git-filter-repo

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        echo "正在清理大于 ${{ inputs.file_size_limit }} 的文件..."
        git filter-repo --strip-blobs-bigger-than ${{ inputs.file_size_limit }} --force

    - name: Compressing and GC
      run: |
        git repack -a -d -f && git prune-packed
        git reflog expire --expire=now --all
        git gc --prune=now --aggressive

    - name: Force Push Changes
      run: |
        git push origin --force --all
        git push origin --force --tags

    - name: Reset History (Orphan Branch)
      run: |
        git checkout --orphan latest_branch
        git add -A
        git commit -m "chore: purge history and cleanup garbage [skip ci]"
        git branch -D main
        git branch -m main

    - name: Force Push to Remote
      run: |
        git push -f origin main
